/* Auto-generated by scripts/build_demo.py — do not edit by hand. */
window.DEMO_DATA = {
  "topics": [
    {
      "key": "work",
      "name": "WORK"
    },
    {
      "key": "food",
      "name": "FOOD"
    },
    {
      "key": "travelling",
      "name": "TRAVELLING"
    },
    {
      "key": "city_life",
      "name": "CITY LIFE"
    },
    {
      "key": "home",
      "name": "HOME"
    },
    {
      "key": "education",
      "name": "EDUCATION"
    },
    {
      "key": "daily_routine",
      "name": "DAILY ROUTINE"
    },
    {
      "key": "family",
      "name": "FAMILY & RELATIVES"
    }
  ],
  "topic_labels": {
    "work": "WORK",
    "food": "FOOD",
    "travelling": "TRAVELLING",
    "city_life": "CITY LIFE",
    "home": "HOME",
    "education": "EDUCATION",
    "daily_routine": "DAILY ROUTINE",
    "family": "FAMILY & RELATIVES"
  },
  "topic_to_scenarios": {
    "food": [
      "food_shared_kitchen",
      "food_eating_out"
    ],
    "city_life": [
      "city_transport",
      "city_public_spaces"
    ],
    "travelling": [
      "travelling_air",
      "travelling_luggage"
    ],
    "work": [
      "work_office"
    ],
    "education": [
      "education_school",
      "education_lunch_break",
      "education_exam_time"
    ],
    "home": [
      "home_house",
      "home_chores_time"
    ],
    "family": [
      "family_relatives"
    ],
    "daily_routine": [
      "daily_routine_day"
    ]
  },
  "scenarios": {
    "food_shared_kitchen": {
      "key": "food_shared_kitchen",
      "topic_key": "food",
      "name": "FOOD — shared kitchen",
      "item_kind": "consumable",
      "nouns": [
        "yoghurt",
        "sandwich",
        "cookie",
        "pizza",
        "apple",
        "egg",
        "snack",
        "cake",
        "chocolate",
        "strawberry",
        "tomato",
        "onion",
        "bacon",
        "chip",
        "crisp",
        "donut",
        "doughnut",
        "ham",
        "hamburger",
        "hot dog",
        "pasta",
        "sausage",
        "steak",
        "yogurt",
        "cereal",
        "melon",
        "mushroom",
        "pea",
        "pear",
        "toast",
        "broccoli",
        "cabbage",
        "cucumber",
        "lettuce",
        "pie",
        "pineapple",
        "spinach"
      ],
      "places": [
        "kitchen",
        "flat",
        "fridge",
        "supermarket",
        "food court"
      ],
      "people": [
        "your best friend",
        "your classmate",
        "your colleague",
        "a neighbour",
        "your roommate"
      ],
      "operations": [
        "addition",
        "subtraction",
        "multiplication",
        "division",
        "percentage"
      ],
      "contexts": [
        {
          "noun": "yoghurt",
          "place": "fridge",
          "city": ""
        },
        {
          "noun": "yoghurt",
          "place": "kitchen",
          "city": ""
        },
        {
          "noun": "sandwich",
          "place": "kitchen",
          "city": ""
        },
        {
          "noun": "pizza",
          "place": "kitchen",
          "city": ""
        },
        {
          "noun": "cookie",
          "place": "supermarket",
          "city": ""
        },
        {
          "noun": "pasta",
          "place": "kitchen",
          "city": ""
        },
        {
          "noun": "toast",
          "place": "kitchen",
          "city": ""
        },
        {
          "noun": "apple",
          "place": "fridge",
          "city": ""
        },
        {
          "noun": "lunch menu",
          "place": "cafeteria",
          "city": ""
        },
        {
          "noun": "dinner set",
          "place": "restaurant",
          "city": ""
        },
        {
          "noun": "set menu",
          "place": "food court",
          "city": ""
        }
      ],
      "cities": [],
      "purchase_items": [
        "lunch menu",
        "dinner set",
        "set menu",
        "main course",
        "coffee and cake deal"
      ],
      "discount_groups": [
        "students",
        "staff",
        "loyalty card holders",
        "seniors"
      ]
    },
    "food_eating_out": {
      "key": "food_eating_out",
      "topic_key": "food",
      "name": "FOOD — eating out",
      "item_kind": "meal",
      "nouns": [
        "starter",
        "dessert",
        "main course",
        "set menu",
        "course"
      ],
      "places": [
        "restaurant",
        "cafeteria",
        "bar",
        "pub",
        "food court"
      ],
      "people": [
        "your diner",
        "your waiter",
        "your waitress"
      ],
      "operations": [
        "addition",
        "subtraction",
        "multiplication",
        "percentage"
      ],
      "contexts": [
        {
          "noun": "set menu",
          "place": "restaurant",
          "city": ""
        },
        {
          "noun": "main course",
          "place": "restaurant",
          "city": ""
        },
        {
          "noun": "starter",
          "place": "restaurant",
          "city": ""
        },
        {
          "noun": "dessert",
          "place": "cafeteria",
          "city": ""
        },
        {
          "noun": "course",
          "place": "restaurant",
          "city": ""
        },
        {
          "noun": "set menu",
          "place": "food court",
          "city": ""
        },
        {
          "noun": "starter",
          "place": "pub",
          "city": ""
        },
        {
          "noun": "dessert",
          "place": "bar",
          "city": ""
        }
      ],
      "cities": [],
      "purchase_items": [
        "set menu",
        "main course",
        "starter",
        "dessert"
      ],
      "discount_groups": [
        "students",
        "staff",
        "loyalty card holders",
        "seniors"
      ]
    },
    "city_transport": {
      "key": "city_transport",
      "topic_key": "city_life",
      "name": "CITY LIFE — transport",
      "item_kind": "ticket",
      "nouns": [
        "bus ticket",
        "metro card",
        "tram pass",
        "travel pass",
        "ticket"
      ],
      "places": [
        "bus station",
        "metro",
        "tram",
        "train station",
        "city square",
        "bus stop",
        "car park",
        "terminal"
      ],
      "people": [
        "a commuter",
        "a passenger",
        "a visitor",
        "your neighbour"
      ],
      "operations": [
        "addition",
        "subtraction",
        "multiplication",
        "percentage"
      ],
      "contexts": [
        {
          "noun": "metro card",
          "place": "metro",
          "city": ""
        },
        {
          "noun": "bus ticket",
          "place": "bus station",
          "city": ""
        },
        {
          "noun": "tram pass",
          "place": "tram",
          "city": ""
        },
        {
          "noun": "travel pass",
          "place": "train station",
          "city": ""
        },
        {
          "noun": "city tour ticket",
          "place": "city square",
          "city": "downtown"
        },
        {
          "noun": "bus ticket",
          "place": "bus station",
          "city": "the city centre"
        },
        {
          "noun": "bus ticket",
          "place": "bus stop",
          "city": ""
        }
      ],
      "cities": [
        "downtown",
        "the city centre",
        "the suburbs",
        "the old town",
        "the business district"
      ],
      "purchase_items": [
        "bus ticket",
        "metro card",
        "tram pass",
        "city tour ticket"
      ],
      "discount_groups": [
        "students",
        "residents",
        "seniors",
        "unemployed residents"
      ]
    },
    "city_public_spaces": {
      "key": "city_public_spaces",
      "topic_key": "city_life",
      "name": "CITY LIFE — public spaces",
      "item_kind": "countable",
      "nouns": [
        "flyer",
        "newspaper",
        "poster",
        "map",
        "leaflet",
        "brochure"
      ],
      "places": [
        "park",
        "museum",
        "library",
        "city square",
        "shopping centre",
        "cafeteria",
        "gallery",
        "mall",
        "bakery",
        "gym",
        "market"
      ],
      "people": [
        "a best friend",
        "a classmate",
        "a colleague",
        "a neighbour",
        "a roommate",
        "a member",
        "a police",
        "a police officer",
        "a policeman",
        "a policewoman",
        "a queen",
        "a champion"
      ],
      "operations": [
        "addition",
        "subtraction",
        "multiplication",
        "division"
      ],
      "contexts": [
        {
          "noun": "flyer",
          "place": "shopping centre",
          "city": ""
        },
        {
          "noun": "newspaper",
          "place": "library",
          "city": ""
        },
        {
          "noun": "poster",
          "place": "museum",
          "city": ""
        },
        {
          "noun": "map",
          "place": "city square",
          "city": ""
        },
        {
          "noun": "flyer",
          "place": "park",
          "city": ""
        },
        {
          "noun": "leaflet",
          "place": "mall",
          "city": ""
        },
        {
          "noun": "brochure",
          "place": "gallery",
          "city": ""
        },
        {
          "noun": "map",
          "place": "market",
          "city": ""
        }
      ],
      "cities": [],
      "purchase_items": [],
      "discount_groups": []
    },
    "travelling_air": {
      "key": "travelling_air",
      "topic_key": "travelling",
      "name": "TRAVELLING — air travel",
      "item_kind": "ticket",
      "nouns": [
        "ticket",
        "boarding card",
        "passport",
        "seat reservation",
        "reservation"
      ],
      "places": [
        "check-in",
        "gate",
        "hall",
        "passport control",
        "terminal"
      ],
      "people": [
        "your attendant",
        "a passenger",
        "your security guard"
      ],
      "operations": [
        "addition",
        "subtraction",
        "multiplication",
        "percentage"
      ],
      "contexts": [
        {
          "noun": "flight ticket",
          "place": "airport",
          "city": "London"
        },
        {
          "noun": "boarding card",
          "place": "gate",
          "city": "Edinburgh"
        },
        {
          "noun": "seat reservation",
          "place": "check-in",
          "city": "Glasgow"
        },
        {
          "noun": "coach ticket",
          "place": "terminal",
          "city": "Manchester"
        }
      ],
      "cities": [
        "Glasgow",
        "Aberdeen",
        "Edinburgh",
        "London",
        "Paris",
        "Berlin",
        "Rome"
      ],
      "purchase_items": [
        "flight ticket",
        "train ticket",
        "coach ticket",
        "seat reservation"
      ],
      "discount_groups": [
        "students",
        "seniors",
        "children",
        "group travellers"
      ]
    },
    "travelling_luggage": {
      "key": "travelling_luggage",
      "topic_key": "travelling",
      "name": "TRAVELLING — luggage",
      "item_kind": "countable",
      "nouns": [
        "suitcase",
        "backpack",
        "guide book",
        "map",
        "souvenir",
        "water bottle",
        "sleeping bag",
        "boarding card"
      ],
      "places": [
        "check-in",
        "gate",
        "hall",
        "passport control",
        "terminal",
        "countryside",
        "gym",
        "location",
        "sauna",
        "twin",
        "vacancy",
        "car park"
      ],
      "people": [
        "your attendant",
        "a passenger",
        "your security guard",
        "your boyfriend",
        "your tour guide"
      ],
      "operations": [
        "addition",
        "subtraction",
        "multiplication",
        "division"
      ],
      "contexts": [
        {
          "noun": "suitcase",
          "place": "airport",
          "city": ""
        },
        {
          "noun": "backpack",
          "place": "train station",
          "city": ""
        },
        {
          "noun": "guide book",
          "place": "hotel",
          "city": ""
        },
        {
          "noun": "map",
          "place": "platform",
          "city": ""
        },
        {
          "noun": "souvenir",
          "place": "hotel",
          "city": ""
        }
      ],
      "cities": [],
      "purchase_items": [],
      "discount_groups": []
    },
    "work_office": {
      "key": "work_office",
      "topic_key": "work",
      "name": "WORK — office",
      "item_kind": "document",
      "nouns": [
        "report",
        "email",
        "task",
        "invoice",
        "contract",
        "appointment",
        "agenda",
        "agreement",
        "application"
      ],
      "places": [
        "office",
        "meeting room",
        "reception",
        "workplace"
      ],
      "people": [
        "your colleague",
        "your manager",
        "your boss",
        "your assistant",
        "a secretary",
        "an accountant",
        "a receptionist"
      ],
      "operations": [
        "addition",
        "subtraction",
        "multiplication",
        "division"
      ],
      "contexts": [
        {
          "noun": "report",
          "place": "office",
          "city": ""
        },
        {
          "noun": "email",
          "place": "office",
          "city": ""
        },
        {
          "noun": "task",
          "place": "office",
          "city": ""
        },
        {
          "noun": "invoice",
          "place": "reception",
          "city": ""
        },
        {
          "noun": "contract",
          "place": "meeting room",
          "city": ""
        },
        {
          "noun": "agenda",
          "place": "workplace",
          "city": ""
        },
        {
          "noun": "application",
          "place": "office",
          "city": ""
        }
      ],
      "cities": [],
      "purchase_items": [],
      "discount_groups": []
    },
    "education_school": {
      "key": "education_school",
      "topic_key": "education",
      "name": "EDUCATION — school",
      "item_kind": "document",
      "nouns": [
        "homework",
        "assignment",
        "certificate",
        "registration form",
        "lesson",
        "desk",
        "computer",
        "result",
        "grade",
        "textbook",
        "essay",
        "quiz",
        "schoolwork"
      ],
      "places": [
        "classroom",
        "school library",
        "study hall",
        "school office"
      ],
      "people": [
        "your head teacher",
        "your headmaster",
        "your headmistress",
        "your native speaker",
        "a pupil",
        "a student",
        "your ancestor",
        "your author",
        "a learner",
        "a schoolchild",
        "your adviser",
        "your historian",
        "your mathematician",
        "your poet",
        "your schoolteacher"
      ],
      "operations": [
        "addition",
        "subtraction",
        "multiplication",
        "division"
      ],
      "contexts": [
        {
          "noun": "homework",
          "place": "classroom",
          "city": ""
        },
        {
          "noun": "assignment",
          "place": "study hall",
          "city": ""
        },
        {
          "noun": "textbook",
          "place": "school library",
          "city": ""
        },
        {
          "noun": "desk",
          "place": "classroom",
          "city": ""
        },
        {
          "noun": "computer",
          "place": "classroom",
          "city": ""
        },
        {
          "noun": "registration form",
          "place": "school office",
          "city": ""
        },
        {
          "noun": "essay",
          "place": "classroom",
          "city": ""
        },
        {
          "noun": "quiz",
          "place": "classroom",
          "city": ""
        }
      ],
      "cities": [],
      "purchase_items": [],
      "discount_groups": []
    },
    "home_house": {
      "key": "home_house",
      "topic_key": "home",
      "name": "HOME — house",
      "item_kind": "countable",
      "nouns": [
        "towel",
        "cushion",
        "book",
        "plate",
        "blanket",
        "key",
        "box",
        "shirt",
        "dress",
        "cupboard",
        "drawer",
        "lamp",
        "basket",
        "candle",
        "carpet",
        "curtain",
        "duvet",
        "jar",
        "kettle"
      ],
      "places": [
        "kitchen",
        "bedroom",
        "hallway",
        "living room",
        "garage",
        "sitting room",
        "entrance",
        "basement"
      ],
      "people": [
        "your best friend",
        "your classmate",
        "your colleague",
        "a neighbour",
        "your roommate",
        "your aunt",
        "your couple",
        "your cousin",
        "your daughter",
        "your grandfather",
        "your grandmother",
        "your husband",
        "your mother-in-law",
        "your nephew",
        "your niece",
        "your parent",
        "your son",
        "your son-in-law",
        "your uncle",
        "your wife",
        "your bride",
        "your relative"
      ],
      "operations": [
        "addition",
        "subtraction",
        "multiplication",
        "division"
      ],
      "contexts": [
        {
          "noun": "towel",
          "place": "hallway",
          "city": ""
        },
        {
          "noun": "book",
          "place": "bedroom",
          "city": ""
        },
        {
          "noun": "plate",
          "place": "kitchen",
          "city": ""
        },
        {
          "noun": "key",
          "place": "hallway",
          "city": ""
        },
        {
          "noun": "cushion",
          "place": "sitting room",
          "city": ""
        },
        {
          "noun": "blanket",
          "place": "bedroom",
          "city": ""
        },
        {
          "noun": "mug",
          "place": "kitchen",
          "city": ""
        },
        {
          "noun": "kettle",
          "place": "kitchen",
          "city": ""
        }
      ],
      "cities": [],
      "purchase_items": [],
      "discount_groups": []
    },
    "family_relatives": {
      "key": "family_relatives",
      "topic_key": "family",
      "name": "FAMILY — relatives",
      "item_kind": "countable",
      "nouns": [
        "photo",
        "gift",
        "card",
        "cake",
        "pet",
        "anniversary",
        "wedding"
      ],
      "places": [
        "accommodation",
        "beach",
        "building",
        "college",
        "district",
        "farmhouse",
        "flat",
        "library",
        "primary school",
        "pub",
        "theme park",
        "university",
        "village",
        "website",
        "capital",
        "casino",
        "destination",
        "distillery",
        "forest",
        "jungle",
        "path",
        "ruins",
        "temple",
        "trail",
        "valley",
        "waterfall",
        "bedroom",
        "laboratory",
        "market",
        "supermarket",
        "post office",
        "airport",
        "earth",
        "hill",
        "museum",
        "space station",
        "arena",
        "circle",
        "entrance",
        "gallery",
        "loft",
        "stalls",
        "wharf",
        "family home",
        "kitchen",
        "garden"
      ],
      "people": [
        "your aunt",
        "your couple",
        "your cousin",
        "your daughter",
        "your grandfather",
        "your grandmother",
        "your husband",
        "your mother-in-law",
        "your nephew",
        "your niece",
        "your parent",
        "your son",
        "your son-in-law",
        "your uncle",
        "your wife",
        "your bride",
        "your relative"
      ],
      "operations": [
        "addition",
        "subtraction",
        "multiplication",
        "division"
      ],
      "contexts": [
        {
          "noun": "photo",
          "place": "family home",
          "city": ""
        },
        {
          "noun": "gift",
          "place": "garden",
          "city": ""
        },
        {
          "noun": "card",
          "place": "kitchen",
          "city": ""
        },
        {
          "noun": "cake",
          "place": "kitchen",
          "city": ""
        }
      ],
      "cities": [],
      "purchase_items": [],
      "discount_groups": []
    },
    "daily_routine_day": {
      "key": "daily_routine_day",
      "topic_key": "daily_routine",
      "name": "DAILY ROUTINE",
      "item_kind": "countable",
      "nouns": [
        "cup of coffee",
        "message",
        "phone call",
        "chore",
        "appointment",
        "meal"
      ],
      "places": [
        "kitchen",
        "bus stop",
        "office",
        "gym",
        "local shop",
        "park"
      ],
      "people": [
        "you",
        "your partner",
        "your colleague",
        "your friend"
      ],
      "operations": [
        "addition",
        "subtraction",
        "multiplication",
        "division"
      ],
      "contexts": [],
      "cities": [],
      "purchase_items": [],
      "discount_groups": []
    },
    "education_lunch_break": {
      "key": "education_lunch_break",
      "topic_key": "education",
      "name": "EDUCATION — lunch break",
      "item_kind": "time",
      "nouns": [
        "lunch"
      ],
      "places": [
        "cafeteria",
        "canteen",
        "food court"
      ],
      "people": [
        "a student",
        "a pupil"
      ],
      "operations": [
        "time_remaining"
      ],
      "contexts": [
        {
          "noun": "lunch",
          "place": "cafeteria",
          "city": ""
        },
        {
          "noun": "lunch",
          "place": "canteen",
          "city": ""
        },
        {
          "noun": "lunch",
          "place": "food court",
          "city": ""
        }
      ],
      "cities": [],
      "purchase_items": [],
      "discount_groups": []
    },
    "education_exam_time": {
      "key": "education_exam_time",
      "topic_key": "education",
      "name": "EDUCATION — exam timing",
      "item_kind": "time",
      "nouns": [
        "exam",
        "examination"
      ],
      "places": [
        "classroom",
        "exam hall",
        "study hall"
      ],
      "people": [
        "a student",
        "a pupil"
      ],
      "operations": [
        "time_percentage"
      ],
      "contexts": [
        {
          "noun": "exam",
          "place": "classroom",
          "city": ""
        },
        {
          "noun": "examination",
          "place": "exam hall",
          "city": ""
        },
        {
          "noun": "exam",
          "place": "study hall",
          "city": ""
        }
      ],
      "cities": [],
      "purchase_items": [],
      "discount_groups": []
    },
    "home_chores_time": {
      "key": "home_chores_time",
      "topic_key": "home",
      "name": "HOME — chore times",
      "item_kind": "time",
      "nouns": [
        "chores"
      ],
      "places": [
        "flat",
        "kitchen",
        "living room"
      ],
      "people": [
        "Jake",
        "Sarah",
        "Alex",
        "Emma",
        "Tom",
        "Lucy"
      ],
      "operations": [
        "time_compare"
      ],
      "contexts": [
        {
          "noun": "chores",
          "place": "flat",
          "city": ""
        },
        {
          "noun": "chores",
          "place": "kitchen",
          "city": ""
        },
        {
          "noun": "chores",
          "place": "living room",
          "city": ""
        }
      ],
      "cities": [],
      "purchase_items": [],
      "discount_groups": []
    }
  }
};
